# alphanet
name: "Alphanetv3GRU"

## dataset
dir_folder: "../stockdata/wukong"
# dir_folder: "../stockdata/sample"



## network 
netname: AlphaNetv3GRU
net_opt:
  in_features: 32
  out_features: 1
  time_length: 30

## train setting
batch_size: 2000
total_epoch: 50
lr: !!float 1e-4

## log setting
exp_dir: "./experiments/"
resume: ~