# FactorNet with New built data
name: "FactorNet-4encoderNewData-RemoveLSTM-wukong220821"

## dataset
# dir_folder: "../stockdata/wukong-220821/"
# dir_folder: "../stockdata/wukong-220817/"
dir_folder: "../stockdata/sample"



## network 
netname: FactorNetLSTM_4encoderRemoveLSTM220911
net_opt:
  in_features: 40
  out_features: 1
  time_length: 30
  # dropout: !!float 0.0 # currently not used

## train setting
batch_size: 2000
total_epoch: 50
lr: !!float 1e-4
each_Tmax: 25
restart_step: 25
warmup_step: 5
eta_min: !!float 1e-7

## log setting
exp_dir: "./experiments/"
resume: ~